console.log(typeof 0)
console.log(typeof true)
console.log(typeof 'JavaScript')
console.log(typeof undefined)
console.log(typeof Math)
console.log(typeof Symbol('35'))
console.log(typeof null)
console.log(typeof function() {})
console.log(typeof NaN)